OmertexBusTicketsSystem/ViewModels/VoyageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OmertexBusTicketsSystem.ViewModels
{
    public class VoyageViewModel
    {
        public int Id { get; set; }
        public string VoyageName { get; set; }
        public DateTime Departure { get; set; }
        public DateTime Arrival { get; set; }
        public string DepartureStop { get; set; }
        public string ArrivalStop { get; set; }
    }
}

OmertexBusTicketsSystem/Controllers/VoyageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OmertexBusTicketsSystem.BL.DTO;
using OmertexBusTicketsSystem.BL.Interfaces;
using OmertexBusTicketsSystem.BL.SearchFilters;
using OmertexBusTicketsSystem.ViewModels;
using OmertexBusTicketsSystem.ViewModelsFactories.Interdaces;

namespace OmertexBusTicketsSystem.Controllers
{
    public class VoyageController : Controller
    {
        private readonly IVoyagesFactory _voyagesFactory;
        private readonly IVoyageService _voyageService;
        private readonly IBusStopService _busStopService;
        private readonly IBusStopsFactory _busStopsFactory;
        private readonly ITicketService _ticketService;
        private readonly ITicketsFactory _ticketsFactory;
        private readonly IOrderService _orderService;
        public VoyageController() { }

        public VoyageController(IVoyagesFactory voyagesFactory, IVoyageService voyageService, IBusStopService busStopService, IBusStopsFactory busStopsFactory, ITicketService ticketService, ITicketsFactory ticketsFactory, IOrderService orderService)
        {
            _voyageService = voyageService;
            _voyagesFactory = voyagesFactory;
            _busStopService = busStopService;
            _busStopsFactory = busStopsFactory;
            _ticketService = ticketService;
            _ticketsFactory = ticketsFactory;
            _orderService = orderService;
        }
        [Authorize]
        public ActionResult SearchVoyages()
        {
            List<BusStopModel> res = new List<BusStopModel>();
            var stops = _busStopService.GetAllBusStops();
            foreach (var element in stops)
            {
                res.Add(_busStopsFactory.Get(element));
            }
            SelectList slList = new SelectList(res, "Id", "Name");
            ViewBag.stops = slList;
            return View();
        }
        [Authorize]
        public ActionResult ApplyFilter(int? idArrivalStop, int? idDepartureStop, DateTime? from, DateTime? till)
        {
            var filter = new VoyagesSearchFilters()
            {
                FromDateTime = from,
                TillDateTime = till,
                ArrivalStopId = idArrivalStop,
                DepartureStopId = idDepartureStop
            };
            var res = _voyageService.GetVoyagesByFilter(filter);
            List<VoyageViewModel> models = new List<VoyageViewModel>();
            foreach (var element in res)
            {
                models.Add(_voyagesFactory.Get(element));
            }
            return PartialView(models);
        }
        // GET: Voyage
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        // GET: Voyage/Details/5
        public ActionResult ReserveTickets(int id)
        {
            var temp = _ticketService.GetFreeTicketsByVoyageId(id);
            List<TicketSimpleViewModel> models = new List<TicketSimpleViewModel>();
            foreach (var element in temp)
            {
                models.Add(_ticketsFactory.GetSimple(element));
            }
            TicketsContainerViewModel result = _ticketsFactory.GetModels(models);
            var voyage = _voyageService.GetVoyageById(id);
            var voyageView = _voyagesFactory.Get(voyage);
            ViewBag.voyage = voyageView;
            
            return View(result);
        }
        [Authorize]
        [HttpPost]
        public ActionResult ReserveTickets(TicketsContainerViewModel containerViewModel)
        {
            try
            {
                OrderDto order = new OrderDto();
                List<TicketDto> myList = new List<TicketDto>();
                foreach (var element in containerViewModel.TicketSimple)
                {
                    if (element.Checked == true) myList.Add(_ticketsFactory.GeTicketDto(element));
                }
                order.UserId = User.Identity.GetUserId();
                order.Tickets = myList;
                
               _orderService.MakeOrder(order);
               // _ticketService.ReserveTickets(myList, UserId);
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }


    }
}

OmertexBusTicketsSystem/Views/Voyage/ApplyFilter.cshtml
@model IEnumerable<OmertexBusTicketsSystem.ViewModels.VoyageViewModel>

<table border="1">
    @foreach (var item in Model)
    {

        <tr>
            <td>@item.VoyageName</td>
            <td>@item.Departure</td>
            <td>@item.DepartureStop</td>
            <td>@item.Arrival</td>
            <td>@item.ArrivalStop</td>
            <td>
                @Html.ActionLink("Reserve Tickets", "ReserveTickets", new { id=item.Id }) |
            </td>
        </tr>

    }
</table>

OmertexBusTicketsSystem/Views/Voyage/ReserveTickets.cshtml
@model OmertexBusTicketsSystem.ViewModels.TicketsContainerViewModel

@{
    ViewBag.Title = "ReserveTickets";
}

<h2>ReserveTickets</h2>

Voyage name: @ViewBag.voyage.VoyageName<br />
Bus Stop Departure: @ViewBag.voyage.DepartureStop<br/>
Departure Datetime: @ViewBag.voyage.Departure<br/>
Bus Stop Arrival: @ViewBag.voyage.ArrivalStop<br/>
Arrival Datetime: @ViewBag.voyage.Arrival<br />

<br />

@using (Html.BeginForm("ReserveTickets", "Voyage"))
{
    <table width="50">
        <thead>    Seat number in bus</thead>

        @for (int i = 0; i < Model.TicketSimple.Count; i++)
        {
            <tr>
                <td>
                    @Html.CheckBoxFor(m => Model.TicketSimple[i].Checked)
                    @Model.TicketSimple[i].SeatNumber.ToString()
                    @Html.HiddenFor(m => Model.TicketSimple[i].Id)
                    @Html.HiddenFor(m => Model.TicketSimple[i].Info)


                </td>
            </tr>
        }
        <tr>
            <td>
                <input type="submit" value="Submit"/>
            </td>
        </tr>
      
    </table>
}

OmertexBusTicketsSystem/Views/Voyage/SearchVoyages.cshtml
@model OmertexBusTicketsSystem.BL.SearchFilters.VoyagesSearchFilters

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>jQuery UI Datepicker - Default functionality</title>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function() {
            var $j = jQuery.noConflict();
            $j("#datepicker").datepicker();
        });
    </script>
</head>

<body>

    <br/>
<p>
    Select Departure Stop

    @Html.DropDownList("idDepartureStop", ViewBag.stops as SelectList)
</p>
<p>
    Select Arrival Stop
    @Html.DropDownList("idArrivalStop", ViewBag.stops as SelectList)
</p>
<br/>
Enter datetime From: <input type="datetime" id="from" name="from"><br /><br />

Enter datetime Till:  <input type="datetime" id="till" name="till"><br /><br />

<input type='button' id="submit" value='Поиск'/>
<div id="results"></div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#submit').click(function(e) {
            e.preventDefault();
            var idDepartureStop = $('#idDepartureStop').val();
            idDepartureStop = encodeURIComponent(idDepartureStop);

            var idArrivalStop = $('#idArrivalStop').val();
            idArrivalStop = encodeURIComponent(idArrivalStop);

            var from = $('#from').val();
            from = encodeURIComponent(from);

            var till = $('#till').val();
            till = encodeURIComponent(till);

            $('#results').load("/voyage/ApplyFilter?" +
                "idDepartureStop=" + idDepartureStop +
                "&idArrivalStop=" + idArrivalStop +
                "&from=" + from +
                "&till=" + till
            );
        });
    });
</script>
</body>
</html>